// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIREH9cUFYn409Sh9VzqJeAvocZ8liTKs',
    appId: '1:755578397573:web:58d5186e3888282f5e9aec',
    messagingSenderId: '755578397573',
    projectId: 'trustme-620f1',
    authDomain: 'trustme-620f1.firebaseapp.com',
    storageBucket: 'trustme-620f1.firebasestorage.app',
    measurementId: 'G-WSX2M60VYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKCTCvBBDuWsgwAhHYRSTO9MDa2AG1tY',
    appId: '1:755578397573:android:71c81c4b804baf6b5e9aec',
    messagingSenderId: '755578397573',
    projectId: 'trustme-620f1',
    storageBucket: 'trustme-620f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB429-L1Qt4PBEOPIltCKUY0J9R6lQbxXM',
    appId: '1:755578397573:ios:a46b49a5db77f2685e9aec',
    messagingSenderId: '755578397573',
    projectId: 'trustme-620f1',
    storageBucket: 'trustme-620f1.firebasestorage.app',
    iosBundleId: 'com.example.trustmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB429-L1Qt4PBEOPIltCKUY0J9R6lQbxXM',
    appId: '1:755578397573:ios:a46b49a5db77f2685e9aec',
    messagingSenderId: '755578397573',
    projectId: 'trustme-620f1',
    storageBucket: 'trustme-620f1.firebasestorage.app',
    iosBundleId: 'com.example.trustmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIREH9cUFYn409Sh9VzqJeAvocZ8liTKs',
    appId: '1:755578397573:web:09f704cf362aa4cc5e9aec',
    messagingSenderId: '755578397573',
    projectId: 'trustme-620f1',
    authDomain: 'trustme-620f1.firebaseapp.com',
    storageBucket: 'trustme-620f1.firebasestorage.app',
    measurementId: 'G-MPTHX2YFFV',
  );
}
